import FooterComponent from "@/components/footer";
import HeaderComponent from "@/components/header";
import localFont from "next/font/local";
import { Metadata } from "next/types";
import "./globalicons.css";
import "./globals.css";

const myPrimaryFont = localFont({
  src: "../public/fonts/Satoshi-Variable.ttf",
  variable: "--font-satoshi",
});
const mySecondaryFont = localFont({
  src: "../public/fonts/Gambetta-Variable.ttf",
  variable: "--font-gambetta",
});

const myTertiaryFont = localFont({
  src: "../public/fonts/Chillax-Variable.ttf",
  variable: "--font-chillax",
});

export const metadata: Metadata = {
  title: "Bruno Truong",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={
          (myPrimaryFont.variable,
          mySecondaryFont.variable,
          myTertiaryFont.variable)
        }
      >
        <div>
          <HeaderComponent />
          {children}
          <FooterComponent />
        </div>
      </body>
    </html>
  );
}
